### ISSUE TITLE
Add support for 'oeante'

### ISSUE THREAD

**Issue by jchodera** [choderalab/openmoltools#11]
It would be useful to add (optional) support for the pure-Python 'oeante' alternative to Antechamber: https://simtk.org/home/oeante

It does, however, require the OpenEye tools be installed, but this is fine since it will be optional.

I'm happy to work on this.

**Comment by kyleabeauchamp** [comment]
I think this can be closed for now, as OEAnte is not yet in production.  We can re-open this once OEAnte is fully online and supported.

**Comment by davidlmobley** [comment]
Agreed; as much a fan as I am of the idea of that effort, it is currently dead (no updates since initial version).



—

**Comment by jchodera** [comment]
Resurrection is imminent.

**Comment by davidlmobley** [comment]
Ah, are you guys working on it?

On Wed, Apr 29, 2015 at 8:46 PM, John Chodera <notifications@github.com>
wrote:

> Resurrection is imminent.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/choderalab/openmoltools/issues/11#issuecomment-97652835>
> .
>



-- 
David Mobley
dmobley@gmail.com
949-385-2436
