### ISSUE TITLE
Implement alternate way of choosing box sizes for packmol

### ISSUE THREAD

**Issue by davidlmobley** [choderalab/openmoltools#111]
Currently, the default size box generated by `packmol.pack_box` is deliberately *extremely* conservative (probably the resulting volume is about 8 times larger than strictly necessary in most cases) requiring (as the documentation states) fairly long equilibration times.

Currently, `openmoltools.packmol.pack_box` uses `openmoltools.packmol.approximate_volume` to generate initial box size (edge size) estimates for packmol. This is based on a rough estimate of atomic volumes to calculate molecular volumes, and the final box edge length (estimated from the sum of atomic volumes) is scaled by a factor of 2 (a factor of 8 for volume) by default. 

In the past, I have always handled this issue by estimating volumes based on the density of the components or the expected density of the mixture, or when these are not known or not available, simply based on assuming a density of 1 g/ml. For the simple organic fragment- or drug-like molecules we've used this on this results in reasonable box sizes which seem not to lead to excessive crashing. 

To resolve this issue I will implement a density-based box size estimator for packmol.

**Comment by davidlmobley** [comment]
For the record, I asked @kyleabeauchamp about whether the current approach (with very generous box sizes) has been extensively tested and found to be necessary, and he wrote the following:

>So for the current density benchmark of 246 systems, my current scheme still leads to equilibration failures around 5% of the time (I'm guessing about the exact number, but those jobs would then simply be repeated on the cluster).  In the past, we had "tighter" boxes, but we had a couple of molecules that were causing headaches so we relaxed the sizes a bit.

>I would say that the current choices are the result of an "organic process" that involved some experimentation.  However, things were much less stable when we were doing those experiments, so it's always possible that things could be refined still.

**Comment by jchodera** [comment]
I'd suggest that we first implement a test scheme that ensures any default box generation schemes are robust.  This could include creating a variety of systems (e.g. the ThermoML systems) and ensuring they don't explode.

As @kyleabeauchamp noted, this conservative scheme was intended to be robust, rather than fast.  It is possible that other schemes may be fast and robust, but we want to make sure we don't lose the robustness.

**Comment by davidlmobley** [comment]
My plan was to implement this for use in my group as an *alternative* to what is already there, and proceed with testing, then revisit if we run into problems. If you have ideas on how to make sure the resulting boxes are robust I'd be glad to hear it, but as far as I know the only way to check for this is just to run simulations.

Also, in dialogue with @kyleabeauchamp by e-mail, it seems unclear that the failures he's seen in the past (5% failure rate) are necessarily due to box issues as opposed to other issues (for example, we used to have issues with crashes for molecules containing triple bonds because of issues GROMACS had handling linear bonds).  It could be that relatively smaller box sizes would exacerbate force field/stability issues which might continue to be present even with larger boxes - i.e. the box size may not be the problem. 

Again, if you know a way to test for robustness aside from just trying it (which we intend to do - and have done in the past) I'd be happy to do such tests.

**Comment by jchodera** [comment]
I imagine the best way to quickly check robustness is to grind through a
bunch of systems and make sure the OpenMM energy is not NaN.  If NaN, there
is nothing we can do to via minimization, etc, to make it work.

Not sure if the packmol step is fast or prohibitively expensive to do this
testing via travis, though.

**Comment by davidlmobley** [comment]
Have you guys actually seen cases where packmol gives boxes where the OpenMM energy is NaN? If so then this sounds like a good approach and I could certainly test it out. But before I implement it, I'd like to know whether this actually happens.

I've not run into the equivalent in GROMACS myself though - specifically, I've used packmol to set up several hundred diverse systems with the density-based approach I described, and never ran into systems which had infinite energies or couldn't minimize. In one particular instance long, long ago, I had some peptide systems in a mixed solvent (water plus something else) which wouldn't minimize *well*, but this was a problem with the minimizer and not with the system. I've also run into cases where I tried to pack a system into too small a box (because of botching a volume estimation or something) and had packmol fail. Or I've had it succeed at packing a system into too small a box and had the problems get resolved in equilibration. But I've never run into a case where it succeeded at packing but resulted in a system I couldn't simulate. Maybe you guys have though - it sounds like @kyleabeauchamp 's work has touched far more systems than my "couple hundred".

**Comment by kyleabeauchamp** [comment]
I'm not sure that I've ever encountered such a situation.  I think your intuition of "botched volume estimation" or "crappy minimizer" matches mine.

**Comment by davidlmobley** [comment]
OK, thanks. If there is substantial opposition to having this functionality *available* in openmoltools I can of course put it somewhere else. But given that this is the approach my group already uses to estimate system volumes (and it's less approximate than the current estimation approach, at least if you have some idea of the expected density) and we have substantial experience with it working well for us, I thought it would be helpful to have it in openmoltools. As I said, I didn't change anything about how pack_box behaves -- all I did was add a function to estimate volumes this way, so, while my own experience indicates this is a robust approach, the fact that users would actually have to deliberately choose to use this approach suggests to me that we can safely include it without having to worry too much about this making things non-robust.

Are there still objections to this being included?

**Comment by kyleabeauchamp** [comment]
I have no objections, I think it's good for us to have several options.

**Comment by jchodera** [comment]
> Are there still objections to this being included?

No, certainly not!
