### ISSUE TITLE
Check conda recipe

### ISSUE THREAD

**Issue by jchodera** [choderalab/openmoltools#128]
I think there might be issues with the conda recipe.  Are you guys sure all the requirements are correctly encoded?

For example, why would you list numpy as a [build requirement](https://github.com/choderalab/openmoltools/blob/master/devtools/conda-recipe/meta.yaml#L18) but not as a [run requirement](https://github.com/choderalab/openmoltools/blob/master/devtools/conda-recipe/meta.yaml#L26-L37)?

**Comment by davidlmobley** [comment]
That doesn't make sense to me either, but that's from Kyle or someone
before me. (I hadn't noticed it as I've only paid attention to what I
changed, and these always worked before.).

On Wed, Jun 17, 2015 at 5:06 PM, John Chodera <notifications@github.com>
wrote:

> I think there might be issues with the conda recipe. Are you guys sure all
> the requirements are correctly encoded?
>
> For example, why would you list numpy as a build requirement
> <https://github.com/choderalab/openmoltools/blob/master/devtools/conda-recipe/meta.yaml#L18>
> but not as a run requirement
> <https://github.com/choderalab/openmoltools/blob/master/devtools/conda-recipe/meta.yaml#L26-L37>
> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/choderalab/openmoltools/issues/128>.
>



-- 
David Mobley
Associate Professor
Department of Pharmaceutical Sciences
Department of Chemistry
3134B Natural Sciences I
University of California, Irvine
Irvine, CA 92697
dmobley@uci.edu
work (949) 824-6383
cell (949) 385-2436

**Comment by jchodera** [comment]
No problem.  It is just something someone familiar with the current state
of things will want to look over at some point.

**Comment by kyleabeauchamp** [comment]
The numpy thing shouldn't really matter AFAIK.  We may have had some things jumping between optional and required dependencies, which is presumably one source of confusion.  Also, parmed is undergoing a major API revision.

**Comment by davidlmobley** [comment]
The changes in this release of openmoltools reflect the latest changes to parmed.



—
