### ISSUE TITLE
Set up secure OpenEye Toolkit tests on travis

### ISSUE THREAD

**Issue by jchodera** [choderalab/openmoltools#136]
I think I know how to do this now, so this is just a reminder for me to do this.

**Comment by jchodera** [comment]
Working on this now.  Need to make some direct commits to the repo to debug.

**Comment by jchodera** [comment]
Thanks to @craigbruce who pointed out the [whole-file encryption abilities of travis-ci](http://docs.travis-ci.com/user/encrypting-files/), we now have OpenEye tools being installed into the miniconda environment that is installed and configured when the travis session starts (thanks Craig!).

Currently, however, the only testing is performed when the `openmoltools-dev` conda package is built, and this is done in a special environment that doesn't have access to the environment with `oechem` installed within it.  I'm working on adding a second set of `nosetests` that will run the complete set of tests again after installing `openmoltools-dev`.  We can also install other optional dependencies like `packmol` if this would be useful.

**Comment by jchodera** [comment]
Something still seems to be amiss, despite the license file being installed, `$OE_LICENSE` being set, and `import openeye.oechem` working.  It must be failing during the delayed import of the toolkits for some reason.  Still debugging.

**Comment by kyleabeauchamp** [comment]
Presumably you could add a standalone script `check_oe_license.py` and have travis run that independent of the `openmoltools` stuff, could be useful for debugging.

**Comment by jchodera** [comment]
Will have to try that.  The simple test of ‘python -c "import openeye.oechem" ‘ worked fine, so it must be failing in a more subtle way.  Will duplicate some code from ‘test_oechem.py‘ to debug.

**Comment by bas-rustenburg** [comment]
Just to double-check, our license recently expired. Are you using the
latest one?
I think importing openeye works regardless of a license.

**Comment by jchodera** [comment]
Ha!  That's exactly the problem---I forgot to update my *own* license!

**Comment by jchodera** [comment]
OK, this is working now.  We install and test with `openeye` and `packmol`, but are missing `checkmol`, `openbabel`, and `rdkit`.  I can add those if they are pip- or conda-installable, but closing this for now.

**Comment by kyleabeauchamp** [comment]
Rdkit is available on binstar, not sure which version and platform

**Comment by jchodera** [comment]
I will look

**Comment by kyleabeauchamp** [comment]
Alternatively you could just deprecate the RDKIT code paths.  I don't think anyone is using them anymore, and it's probably not worth the trouble of maintaining them.

**Comment by davidlmobley** [comment]
I'd be OK with that. They might get resurrected eventually, but at this
point we're focusing entirely on the OE stuff.

On Thu, Jul 2, 2015 at 4:55 PM, Kyle Beauchamp <notifications@github.com>
wrote:

> Alternatively you could just deprecate the RDKIT code paths. I don't think
> anyone is using them anymore, and it's probably not worth the trouble of
> maintaining them.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/choderalab/openmoltools/issues/136#issuecomment-118196557>
> .
>



-- 
David Mobley
Associate Professor
Department of Pharmaceutical Sciences
Department of Chemistry
3134B Natural Sciences I
University of California, Irvine
Irvine, CA 92697
dmobley@uci.edu
work (949) 824-6383
cell (949) 385-2436

**Comment by craigbruce** [comment]
@jchodera - glad I could help!

**Comment by davidlmobley** [comment]
@jchodera - currently Travis-CI seems to fail since this was set up. Are you planning on troubleshooting in the near future, or should we temporarily remove this until you have time to look at it?

**Comment by jchodera** [comment]
Sorry, let me look.  This was working when I finished.

**Comment by jchodera** [comment]
OK, I think I've fixed this.  Will have to see if tests pass.

**Comment by jchodera** [comment]
Monitor travis build here:
https://travis-ci.org/choderalab/openmoltools/builds/70101692

**Comment by jchodera** [comment]
This appears to be fixed now.

**Comment by coleb** [comment]
To clarify what might be a misunderstanding. ‘python -c "import openeye.oechem" ‘  is intentionally allowed to work without any OpenEye license. 

The only true way to test whether OEChem is licensed is by calling the OEChemIsLicensed function: 

$ python -c "from openeye.oechem import OEChemIsLicensed; print OEChemIsLicensed()"
True

**Comment by jchodera** [comment]
Thanks!  We use this idiom in our nosetests to check whether we should run OpenEye tests:
https://github.com/choderalab/openmoltools/blob/master/openmoltools/tests/test_openeye.py#L17-L28
```
try:
    oechem = utils.import_("openeye.oechem")
    if not oechem.OEChemIsLicensed(): raise(ImportError("Need License for OEChem!"))
    oequacpac = utils.import_("openeye.oequacpac")
    if not oequacpac.OEQuacPacIsLicensed(): raise(ImportError("Need License for oequacpac!"))
    oeiupac = utils.import_("openeye.oeiupac")
    if not oeiupac.OEIUPACIsLicensed(): raise(ImportError("Need License for OEOmega!"))        
    oeomega = utils.import_("openeye.oeomega")
    if not oeomega.OEOmegaIsLicensed(): raise(ImportError("Need License for OEOmega!"))    
    HAVE_OE = True
except:
    HAVE_OE = False

...

@skipIf(not HAVE_OE, "Cannot test openeye module without OpenEye tools.")
def test_mytest1():
   ...
```
