### ISSUE TITLE
Tools using tleap need to check target filenames for tleap compatibility

### ISSUE THREAD

**Issue by davidlmobley** [choderalab/openmoltools#137]
Certain filenames are incompatible with `tleap` (i.e. filenames containing spaces, but there are also other examples). Tools using `tleap` (especially in the `amber` module but there may be others) need to check that target filenames are `tleap`-compatible and raise a helpful exception if not. Currently these errors *are* caught but only later in the process, and the error messages are not particularly helpful.

See also https://github.com/MobleyLab/SolvationToolkit/issues/31. Currently we're working there on identifying a full list of characters which are not valid in `tleap` filenames.

**Comment by jchodera** [comment]
I think we should only ever be running tleap in a temporary directory using hardcover filenames.  Input files should be staged into this tempdir and under these hard coded filenames.

**Comment by davidlmobley** [comment]
That's a good point. We've got the temporary directory thing down (and it's clearly necessary since that way we avoid spewing excess files everywhere), but the hard coded filenames is a good idea. 

I wonder if we need to still address aspects of this, though. i.e. are there characters someone might attempt to use in a filename (because they occur in IUPAC names for example) which would cause problems if they are used in filenames? For example, if I use a hardcoded filename for tleap but then copy to a file named by a target IUPAC name (a bad idea, IMO, but someone will attempt it) will certain characters cause it to fail?
