### ISSUE TITLE
Do you want to be pulling OpenEye-toolkits betas with '--pre'?

### ISSUE THREAD

**Issue by coleb** [choderalab/openmoltools#148]
Noticed this in the .travis.yml:

```
pip install --pre -i https://pypi.binstar.org/openeye/simple openeye-toolkits
```

In about a month we'll be pushing up betas for the 2015.Oct toolkit release, at that point you'll start picking up the beta for 2015.Oct instead of the official 2015.Jun release. Not sure this is what you intend. Appreciate the beta-testing if you do intend to do it though. :-)

**Comment by jchodera** [comment]
Thanks, @coleb!  We're happy to make sure this works with the `2015.Oct` release.  The `.travis.yml` environment is supposed to make sure things work on the bleeding edge.  :)
