### ISSUE TITLE
no module named openmm.app.element

### ISSUE THREAD

**Issue by mrshirts** [choderalab/openmoltools#150]
After running 

conda config --add channels http://conda.binstar.org/omnia
conda install openmoltools

And running 

nosetests openmoltools -v --exe

I got: 

ERROR: Failure: ImportError (No module named openmm.app.element)

Any suggestions?  I must be doing something silly here . . .

**Comment by jchodera** [comment]
I don't see this error on `linux`.

I think you might have an outdated version of some dependency.  We probably haven't done a good job of specifying minimum version numbers for dependencies in the [conda recipe](https://github.com/omnia-md/conda-recipes/blob/master/openmoltools/meta.yaml#L14-L37).

I bet you need `openmm>=6.3`, for example.  Try this:
```
conda clean -plts --yes
conda update --yes openmm parmed openmoltools
```

**Comment by mrshirts** [comment]
Thanks for jumping in quick.  This is on OS X, don't know if that matters.

Ran the two commands listed, and openmm now is shown by conda as 6.3, but
the error still occurs: explicitly:

======================================================================

ERROR: Failure: ImportError (No module named openmm.app.element)

----------------------------------------------------------------------

Traceback (most recent call last):

  File
"/Users/mrshirts/anaconda/lib/python2.7/site-packages/nose/loader.py", line
402, in loadTestsFromName

    module = resolve_name(addr.module)

  File "/Users/mrshirts/anaconda/lib/python2.7/site-packages/nose/util.py",
line 311, in resolve_name

    module = __import__('.'.join(parts_copy))

  File
"/Users/mrshirts/anaconda/lib/python2.7/site-packages/openmoltools-0.6.8-py2.7.egg/openmoltools/__init__.py",
line 28, in <module>

    from openmoltools import amber_parser, system_checker, utils, packmol,
openeye, amber, cirpy, gromacs

  File
"/Users/mrshirts/anaconda/lib/python2.7/site-packages/openmoltools-0.6.8-py2.7.egg/openmoltools/amber_parser.py",
line 4, in <module>

    import simtk.openmm.app.element as element

ImportError: No module named openmm.app.element


----------------------------------------------------------------------

Ran 1 test in 0.001s


FAILED (errors=1)

**Comment by rmcgibbo** [comment]
Can you post the output of:
- `python -c 'import simtk'`, 
- python -c 'import simtk.openmm'`
- python -c 'import simtk.openmm.app'`

**Comment by mrshirts** [comment]
python -c 'import simtk.openmm' fails, so it looks like I have an old simtk. . . I'll work on figuring out how to update that.

**Comment by rmcgibbo** [comment]
Run `$ python -c 'import site; print(site.getsitepackages()[0])'`, take a look in the resulting directory (the site-packages) directory), and `rm -rf` anything named simtk or openmm, then re-conda-install openmm.

**Comment by mrshirts** [comment]
Took a few rounds of uninstalling/deleting/reinstalling for everything to get recognized, but seems to work now.  Thanks!

**Comment by jchodera** [comment]
Sometimes, it's easiest to just start with a fresh [miniconda](http://conda.pydata.org/miniconda.html) install, add the omnia channel, and then install what you need.  :)
