### ISSUE TITLE
Inappropriate OpenEye error handling?

### ISSUE THREAD

**Issue by bas-rustenburg** [choderalab/openmoltools#157]
This [line](https://github.com/choderalab/openmoltools/blob/b1ed5f67a4e816a291d60995b3a2934290e710b6/openmoltools/openeye.py#L226) gives me an error. 

Shouldn't `0` indicate success?

```
Warning: failed to build structure for molecule 
Traceback (most recent call last):
  File "parametrize.py", line 17, in <module>
    x = openmoltools.openeye.get_charges(mols[0])
  File "/home/bas/miniconda3/envs/py2k/lib/python2.7/site-packages/openmoltools-0.6.9-py2.7.egg/openmoltools/openeye.py", line 51, in get_charges
    charged_copy = generate_conformers(molecule, max_confs=max_confs, strictStereo=strictStereo)  # Generate up to max_confs conformers
  File "/home/bas/miniconda3/envs/py2k/lib/python2.7/site-packages/openmoltools-0.6.9-py2.7.egg/openmoltools/openeye.py", line 227, in generate_conformers
    raise(RuntimeError("omega returned error code %d" % status))
RuntimeError: omega returned error code 0

**Comment by davidlmobley** [comment]
Nope.

In [1]: from openeye.oechem import *
In [2]: from openeye.oeiupac import *
In [3]: mol = OEMol()
In [4]: OEParseIUPACName(mol, 'phenol')
Out[4]: True
In [6]: from openeye.oeomega import *
In [7]: omega = OEOmega()
In [8]: omega(mol)
Out[8]: True

I use the code you're talking about routinely. The fact that it's raising
an exception means there is something wrong with the molecule you are
feeding into it. Possibly, OE can't understand the molecule, or it has
unspecified stereochemistry.

David


On Tue, Oct 27, 2015 at 12:49 PM, Bas Rustenburg <notifications@github.com>
wrote:

> This line
> <https://github.com/choderalab/openmoltools/blob/b1ed5f67a4e816a291d60995b3a2934290e710b6/openmoltools/openeye.py#L226>
> gives me an error.
>
> Shouldn't 0 indicate success?
>
> Warning: failed to build structure for molecule
> Traceback (most recent call last):
>   File "parametrize.py", line 17, in <module>
>     x = openmoltools.openeye.get_charges(mols[0])
>   File "/home/bas/miniconda3/envs/py2k/lib/python2.7/site-packages/openmoltools-0.6.9-py2.7.egg/openmoltools/openeye.py", line 51, in get_charges
>     charged_copy = generate_conformers(molecule, max_confs=max_confs, strictStereo=strictStereo)  # Generate up to max_confs conformers
>   File "/home/bas/miniconda3/envs/py2k/lib/python2.7/site-packages/openmoltools-0.6.9-py2.7.egg/openmoltools/openeye.py", line 227, in generate_conformers
>     raise(RuntimeError("omega returned error code %d" % status))
> RuntimeError: omega returned error code 0
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/choderalab/openmoltools/issues/157>.
>



-- 
David Mobley
Associate Professor
Department of Pharmaceutical Sciences
Department of Chemistry
3134B Natural Sciences I
University of California, Irvine
Irvine, CA 92697
dmobley@uci.edu
work (949) 824-6383
cell (949) 385-2436

**Comment by bas-rustenburg** [comment]
So they return `0` on an error? ... :unamused:  Thanks! I'll close this then.

**Comment by davidlmobley** [comment]
Really, they return False. But somebody wrote this code so that it prints
False as a digit, oddly enough. (So 0 or 1 rather than True or False).

On Tue, Oct 27, 2015 at 12:57 PM, Bas Rustenburg <notifications@github.com>
wrote:

> So they return 0 on an error? ... [image: :unamused:] Thanks! I'll close
> this then.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/choderalab/openmoltools/issues/157#issuecomment-151625113>
> .
>



-- 
David Mobley
dmobley@gmail.com
949-385-2436

**Comment by bas-rustenburg** [comment]
Ah, I see. Thanks for the explanation David!
