### ISSUE TITLE
Make normalizing molecule optional (openeye.get_charges)

### ISSUE THREAD

**Issue by bas-rustenburg** [choderalab/openmoltools#158]
I would like to generate charges for my molecule using `get_charges`, but I notice that there is no option to not normalize, which among more useful things, overwrites the molecule name. The command `openeye.normalize_molecule` is always called. Any objection to making that optional, with the current behavior as the default?

I can make a PR to implement this.

**Comment by davidlmobley** [comment]
Sounds great.

**Comment by bas-rustenburg** [comment]
Opened a PR #159
