### ISSUE TITLE
Check if amber installed

### ISSUE THREAD

**Issue by andrrizzi** [choderalab/openmoltools#160]
I was wondering if it was useful to create a simple function that checks if AMBER is installed. Right now I'm using ``amber.find_gaff_dat()`` which raises an exception when AMBER is not found, but I think it would be cleaner to have something as simple as
```python
try:
    import shutil.which as which  # Python 3
except ImportError:
    import distutils.spawn.find_executable as which

def is_amber_installed():
    if which('antechamber') is None:
        return False
   return True
```
If this is of interest, I can create a PR.

**Comment by davidlmobley** [comment]
Yes, this ought to be done. Probably at the same time, though, you should be checking for other prerequisites.

This is probably already handled somewhat in that the checks will fail if someone doesn't have AMBER installed, though the failure may need to be more prominent/earlier.

Note that anyone installing via conda ought not to have to worry about this.

**Comment by andrrizzi** [comment]
Good point about the conda installation, I didn't think about it.
