### ISSUE TITLE
Add option to override residue names to amber.run_antechamber

### ISSUE THREAD

**Issue by bas-rustenburg** [choderalab/openmoltools#173]
I have a use for an option to store molecule names inside of the output files produced by [`openmoltools.amber.run_antechamber`](https://github.com/choderalab/openmoltools/blob/master/openmoltools/amber.py#L286).

I will take a stab at implementing it myself if there is interest.

I propose adding an `override_resname` option to specify that the name should be replaced, defaulting to the old behavior to prevent breaking existing workflows. It should be relatively straightforward to use antechamber's `-rn` flag (override residue name) in combination with the already supplied `molecule_name`.

**Comment by davidlmobley** [comment]
Yes, though beware that residue names tend to be easily lost (i.e. OpenEye
tools often removes residue names from .mol2 files). I certainly don't see
a problem with what you propose, though.

On Fri, Jan 15, 2016 at 2:44 PM, Bas Rustenburg <notifications@github.com>
wrote:

> I have a use for an option to store molecule names inside of the output
> files produced by openmoltools.amber.run_antechamber
> <https://github.com/choderalab/openmoltools/blob/master/openmoltools/amber.py#L286>
> .
>
> I will take a stab at implementing it myself if there is interest.
>
> I propose adding an override_resname option to specify that the name
> should be replaced, defaulting to the old behavior to prevent breaking
> existing workflows. It should be relatively straightforward to use
> antechamber's -rn flag (override residue name) in combination with the
> already supplied molecule_name.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/choderalab/openmoltools/issues/173>.
>



-- 
David Mobley
Associate Professor
Department of Pharmaceutical Sciences
Department of Chemistry
3134B Natural Sciences I
University of California, Irvine
Irvine, CA 92697
dmobley@uci.edu
work (949) 824-6383
cell (949) 385-2436

**Comment by jchodera** [comment]
> I propose adding an override_resname option to specify that the name should be replaced

Sounds good, but you can just call the option `resname`.

**Comment by bas-rustenburg** [comment]
Okay! I'll put in a PR.
