### ISSUE TITLE
Remove logging configuration in openmoltools modules

### ISSUE THREAD

**Issue by andrrizzi** [choderalab/openmoltools#194]
Is there a particular reason why ``logging`` is configured within ``openmoltools``'s modules (e.g. [amber.py](https://github.com/choderalab/openmoltools/blob/master/openmoltools/amber.py#L13))?

As ``openmoltools`` is a library and not an application, I would tend to leave ``logging`` configurations to the library user. Otherwise we risk to overwrite the user's ``logging`` configuration when ``openmoltools`` is imported.

**Comment by jchodera** [comment]
Good point. It may have been just for debugging. Let's go ahead and remove it.

**Comment by davidlmobley** [comment]
Agreed.

**Comment by andrrizzi** [comment]
Ok, I'll include it with the next PR then.
