### ISSUE TITLE
py3.5 error

### ISSUE THREAD

**Issue by jchodera** [choderalab/openmoltools#202]
I see that we're now failing on py3.5 with:
```
Failure: SystemError (<built-in function delete_System> returned a result with an error set) ... ERROR
```
but without more explicit information on what went wrong.  Any ideas?  Is this an openeye issue?

**Comment by andrrizzi** [comment]
The test fails only when it is generated. It passes if you don't yield partial functions but just call `check_system_generator`. It looks like `nose` still have few problems with fancy features in python 3.5.

**Comment by andrrizzi** [comment]
Ok, this is probably a problem due to how `OpenMM` systems are kept in the memory. Creating the system in the test rather than in the generator seems to fix it. I'll open a PR to make the changes.

**Comment by jchodera** [comment]
Thanks so much for fixing this!
