### ISSUE TITLE
Keep old indices somewhere after generateOEMolFromTopologyResidue

### ISSUE THREAD

**Issue by pgrinaway** [choderalab/openmoltools#203]
It'd be pretty helpful if the atoms in the `OEMol` had a data entry such as `old_idx` with the index of that atom in the complete system. I think this would be a pretty quick and non-intrusive enhancement--happy to add it myself if it sounds ok to other people.

**Comment by jchodera** [comment]
Go for it!  Maybe `topology_index` instead?

**Comment by pgrinaway** [comment]
sounds good!

**Comment by pgrinaway** [comment]
Resolved in #204
