### ISSUE TITLE
OpenEye beta will fail on travis due to ubuntu compatibility

### ISSUE THREAD

**Issue by davidlmobley** [choderalab/openmoltools#219]
Testing SolvationToolkit, I found that the OpenEye beta toolkits fail to install because the latest beta (2016.6b3) is missing the build for the ubuntu version (12.04) normally used for this; they only have a ubuntu 14 build.  This will affect `openmoltools` the next time we submit a PR, I believe. 

I've asked OpenEye support about this about this to see if they are ceasing support for ubuntu 12.04.

If needed it looks like there may be a way to shift to testing on ubuntu 14 (https://docs.travis-ci.com/user/ci-environment/) if we need to via the "Trusty Beta" environment.

If you want to see the full details, this came up here: https://travis-ci.org/MobleyLab/SolvationToolkit/jobs/126731293

**Comment by jchodera** [comment]
I believe the travis docker infrastructure (which you get with [`sudo: false`](https://github.com/choderalab/openmoltools/blob/master/.travis.yml#L2) uses ubuntu 14.04, so we might be fine.

**Comment by davidlmobley** [comment]
OK. It sounded like there were workarounds. This was more of a "heads up" that the next time someone submits a PR, travis will report that the OE beta builds are broken and this will have to be dealt with.

**Comment by davidlmobley** [comment]
They've temporarily re-added support for the older Ubuntu, though it will be dropped in the future. So this is being closed for now.

At some point they are also going to start removing the beta releases between major releases.

**Comment by jchodera** [comment]
Not sure how best to deal with the beta removal other than to comment out the travis branches when that happens.
