### ISSUE TITLE
Fixing packmol tests to work without RDKit

### ISSUE THREAD

**Issue by davidlmobley** [choderalab/openmoltools#221]
I need to fix the `packmol` tests to work without RDKit. Currently, the tests (if RDKit is available) pack a couple of boxes, generate ffxml files, and run a very short MD simulation. For the forcefield, the (no longer used?) `utils.smiles_to_mdtraj_ffxml(smiles_list)` RDKit functionality is used. 

I see two options to fix the tests and would like input on which to use:
a) Simply test packing of boxes without running simulations, hence not requiring any `ffxml` data
b) Replace the RDKit functionality for getting ffxml data with something else - i.e. your (old?) `oemols_to_ffxml` functionality, or something (newer?) in `forcefield_generators`, and otherwise keep the tests at present. I've not used either of these ffxml generators and am not sure how functional they are at present.

Comments? 

Thanks.

**Comment by jchodera** [comment]
What if we just fix the RDKit dependency so testing works correctly with
RDKit? What are the hurdles to that?

**Comment by davidlmobley** [comment]
Sounds fine to me! I don't use the RDKit functionality here at all and I
thought you guys didn't either anymore, but it's worth including if you're
not opposed.

Also, RDKit is in general working well for us these days (as noted in the
context of LOMAP) which is another point in favor of including that.
