### ISSUE TITLE
Segmentation fault with `gaffTemplateGenerator`

### ISSUE THREAD

**Issue by gregoryross** [choderalab/openmoltools#226]
The `forcefield_generators.gaffTemplateGenerator` produces warnings before a segmentation fault when I run the commands
```python
forcefield = app.ForceField('gaff.xml')
forcefield.registerTemplateGenerator(gaffTemplateGenerator)
pdb = app.PDBFile("molecule.pdb")
system = forcefield.createSystem(pdb.topology)
```
for PDB files when `molecule.pdb` contains a large molecule (I've tried molecules with 52 and 95 atoms).  These problems do not occur when `molecule.pdb` is benzene.

Specifically, the warnings I get before the segmentation fault are
```
/Users/rossg/miniconda2/lib/python2.7/site-packages/simtk/openmm/app/internal/pdbstructure.py:536: UserWarning: WARNING: duplicate atom (ATOM      3  C   1ED A   1      -3.179   1.679  -0.604  1.00  0.00           C  , ATOM      1  C   1ED A   1      -5.160   2.796  -0.057  1.00  0.00           C  )
  warnings.warn("WARNING: duplicate atom (%s, %s)" % (atom, old_atom._pdb_string(old_atom.serial_number, atom.alternate_location_indicator)))
```
for each atom in the PDB file. The PDB itself does not contain duplicated atoms.

**Comment by jchodera** [comment]
Can you make the input files available? Specifically we need the PDB file.

**Comment by gregoryross** [comment]
Sure. Here's an example PDB renamed as a `.txt` file as github doesn't support `.pdb` files.

[1E_oe.txt](https://github.com/choderalab/openmoltools/files/330108/1E_oe.txt)

**Comment by jchodera** [comment]
OK, the error here is that multiple atoms in the residue have the same name. It is unclear if this is permitted by the PDB spec.  

The simple way to avoid this is to call [`OETriposAtomNames`](https://docs.eyesopen.com/toolkits/python/oechemtk/OEChemFunctions/OETriposAtomNames.html) to assign Tripos atom names to make each atom unique.

**Comment by gregoryross** [comment]
Okay, great. I'll give that a go. Thanks!

**Comment by gregoryross** [comment]
The `gaffTemplateGenerator ` is not throwing up any errors. Thanks again.
