### ISSUE TITLE
Direct manipulation of mol2 files

### ISSUE THREAD

**Issue by andrrizzi** [choderalab/openmoltools#231]
I'd like to include in `openmoltools` few functions to perform simple manipulation of `mol2` files without the need of external dependencies such as openeye. In particular, I need to
* read/modify residue name
* read net charge
* normalize net charge to sum to the nearest integer

Since the library is organized by "tools" rather than functionality, I was thinking about creating a new module called `fileio.py` in which to include functions for direct manipulation.

The implementation would look like
```python
>>> mol2_file = Mol2File('path/to/molecule.mol2')
>>> mol2_file.resname = 'MOL'
>>> mol2_file.resname
MOL
>>> mol2_file.normalize_charge()
>>> mol2_file.net_charge
1.0
```
the first implementation will support only files with a single molecule.

If you agree with this I'll open a PR and implement it.

**Comment by andrrizzi** [comment]
Alternatively, should this be implemented in `parmed` since this is already an `openmoltools` dependency?

**Comment by davidlmobley** [comment]
Yes. In fact, there is already some functionality related to your example in ParmEd at my request. For example, I believe Jason put in something like a fix_charges functionality which adjusts the charges to be closer to an integer.

(This is also in the pipeline from OpenEye, as OpenEye mol2 files did not originally have enough precision in the charges.)

**Comment by davidlmobley** [comment]
See https://github.com/MobleyLab/SolvationToolkit/blob/89bcfa7e11693a20c23f2c7ad8522f3599c0bd81/solvationtoolkit/solvated_mixtures.py#L385 for a use of fix_charges from `parmed`.

And yes, I'm absolutely for putting the functionality you want into parmed rather than here. Parmed is starting to have a much larger life of its own than openmoltools does, so `mol2` manipulation should certainly be handled there if at all possible.

**Comment by davidlmobley** [comment]
The `resname` functionality you want is probably in `parmed` already, too.

**Comment by andrrizzi** [comment]
Terrific! This will save me quite some time, thank you!
