### ISSUE TITLE
Scripts should not go in bin

### ISSUE THREAD

**Issue by wesbarnett** [choderalab/openmoltools#232]
By default if I run `setup.py install` named `generate_example_data.py` and `processAmberForceField.py` end up in `/usr/bin`. They should probably go with the rest of the python package.

**Comment by jchodera** [comment]
These are user-executable scripts, so they should go into the `bin/` directory associated with the python installation (e.g. `$HOME/miniconda/bin` if you're dealing with a [`miniconda`](http://conda.pydata.org/miniconda.html) installation), but:
* I'm not sure quite what these scripts are meant to do
* I don't know if we still need them
* They should probably be installed via the [`entry_points` mechanism](https://chriswarrick.com/blog/2014/09/15/python-apps-the-right-way-entry_points-and-scripts/) instead

Thanks for bringing this to our attention!

**Comment by davidlmobley** [comment]
@jchodera - I don't know about these either.

**Comment by jchodera** [comment]
I think @kyleabeauchamp created them.

**Comment by kyleabeauchamp** [comment]
The combine XML was a contribution from LeePing.  The generate example data script was used to generate some of the example data in `chemicals`.  The processAmberForceField script is a cmdline wrapper for turning amber small molecule files into OpenMM XML.

Re-writing them to use entrypoints would be possible but not as valuable as deciding whether you want to keep these.
