### ISSUE TITLE
Re-license to MIT

### ISSUE THREAD

**Issue by davidlmobley** [choderalab/openmoltools#246]
Currently this is GPL, which is problematic. Can we re-license to MIT or BSD?

**Comment by andrrizzi** [comment]
+1 for MIT

**Comment by Lnaden** [comment]
I'll +1 for MIT

**Comment by davidlmobley** [comment]
Right, what's the procedure? I'm guessing we need to consult everyone who contributed significantly? Probably that mainly means Kyle (since John is certainly on board)?? Do you guys want to kick it off?

(I think this is something to deal with quickly, since the fact that we have other packages which rely on `openmoltools` is probably "corrupting" those in some sense.)

**Comment by Lnaden** [comment]
The procedure is to ask permission to make the change from every contributor. Or at very least, ask for explicit approval within a reasonable time scale with implicit approval given after a certain date. We have done that for a couple packages previously. We can use this thread here.

**Comment by davidlmobley** [comment]
OK, can you instigate?

**Comment by Lnaden** [comment]
Sure

**Comment by Lnaden** [comment]
PR opened
