### ISSUE TITLE
Do a new release

### ISSUE THREAD

**Issue by davidlmobley** [choderalab/openmoltools#257]
We need #254 and #255 in a release and Omnia package soon (I have a PR in another repo that won't pass until the water standardization in #254 is conda-installable, for example, and @nathanmlim needs #255 soon-ish). @andrrizzi - do you want to do one or shall I? Anything else we should get in first?

Thanks.

**Comment by andrrizzi** [comment]
Feel free to go ahead! There's nothing on my end that I need to be included in the release.

@Lnaden, since the moving of omnia to conda-forge has started, is there anything special that must be done to release in the old omnia channel?

**Comment by Lnaden** [comment]
I think this was handled back with 0.8.1, but if not, then most certainly handled with 0.8.2
