### ISSUE TITLE
Update conda recipe to use ambertools

### ISSUE THREAD

**Issue by jchodera** [choderalab/openmoltools#278]
Now that [ambertools 18 is on omnia](https://anaconda.org/omnia/ambertools/files), we should update the `openmoltools` recipe to use `ambertools`.

**Comment by andrrizzi** [comment]
Any objection if I go ahead with this? We need it to resolve choderalab/yank#1046 . Should we make an actual release and include the openeye updates added by @hannahbrucemacdonald or just bump the build number in omnia for now?

**Comment by andrrizzi** [comment]
As a note, `ambertools` is 4 times bigger than `ambermini` (85MB against 21MB).

**Comment by jaimergp** [comment]
Users should refer to the conda-recipe at https://github.com/conda-forge/openmoltools-feedstock/blob/master/recipe/meta.yaml for reference now.
