### ISSUE TITLE
Updates for new OpenMM namespace

### ISSUE THREAD

**Issue by jaimergp** [choderalab/openmoltools#303]
Refer to discussion at https://github.com/choderalab/perses/pull/761#issuecomment-777321676

**Comment by mikemhenry** [comment]
Do we want to try and get this fixed upstream instead of trying to fix it in all of our packages?

**Comment by jaimergp** [comment]
That for sure, but at some point we will need this defensive approach to maintain compatibility with <=7.5 and >7.5.

**Comment by mikemhenry** [comment]
True, it won't be backwards compatible forever! I'm not familiar enough with the ecosystem to know if it would be too much of a burden for end users to just have the next release require >7.5 and move over to the new namespace.

**Comment by jaimergp** [comment]
We can also constrain the pinnings at conda-forge, so all current releases have an upper bound on <7.6.0a0

**Comment by mikemhenry** [comment]
> We can also constrain the pinnings at conda-forge, so all current releases have an upper bound on <7.6.0a0

this + getting the backwards compatibility on the namespace fixed upstream I think will require the least amount of dev time to get things working

**Comment by mikemhenry** [comment]
I'll take a stab on making a PR to fix openmm upstream

**Comment by mikemhenry** [comment]
Tracking openmm backwards compatibility here:
https://github.com/openmm/openmm/issues/3022
