### ISSUE TITLE
Add RESP fit support for charges

### ISSUE THREAD

**Issue by jchodera** [choderalab/openmoltools#36]
Rosa Luirink (@luirink) is interested in using RESP-fit charges (from GAMESS or psi4) to derive charges as well. Maybe we can add this functionality next week.

**Comment by davidlmobley** [comment]
Are there any plans to do this? If not I'd recommend closing for now as it seems a distraction from our main efforts at present.

**Comment by kyleabeauchamp** [comment]
I agree that this should be closed because it would be a massive undertaking and is not part of our standard parameterization pipeline.

**Comment by rmcgibbo** [comment]
I wrote an implementation of RESP as a psi4 plugin -- if anyone later decides to work on this feature, it could be a useful starting place or reference. https://github.com/rmcgibbo/resp2
