### ISSUE TITLE
Atom type name issues for GB

### ISSUE THREAD

**Issue by jchodera** [choderalab/openmoltools#40]
In parameterizing a molecule for simulation with GB, I am running into this problem:
```
Traceback (most recent call last):
  File "tests/test_alchemy.py", line 578, in <module>
    test_systembuilder_lysozyme_pdb_mol2()
  File "tests/test_alchemy.py", line 533, in test_systembuilder_lysozyme_pdb_mol2
    print "%s has %d particles" % (name, thing.system.getNumParticles())
  File "/Users/choderaj/code/yank/install/lib/python2.7/site-packages/yank-0.9.0-py2.7.egg/yank/systembuilder.py", line 176, in system
    self._create_system()
  File "/Users/choderaj/code/yank/install/lib/python2.7/site-packages/yank-0.9.0-py2.7.egg/yank/systembuilder.py", line 164, in _create_system
    self._system = forcefield.createSystem(self._topology, **self.system_creation_parameters)
  File "/Users/choderaj/code/yank/install/lib/python2.7/site-packages/simtk/openmm/app/forcefield.py", line 507, in createSystem
    force.createForce(sys, data, nonbondedMethod, nonbondedCutoff, args)
  File "/Users/choderaj/code/yank/install/lib/python2.7/site-packages/simtk/openmm/app/forcefield.py", line 1245, in createForce
    raise ValueError('No GBSAOBC parameters defined for atom type '+t)
ValueError: No GBSAOBC parameters defined for atom type MOL-C1
```

**Comment by kyleabeauchamp** [comment]
For the near term, I believe we have decided that users must go through AmberTools for setting up GB simulations.

**Comment by jchodera** [comment]
Correct.  Is it all right if I create an issue to remind me that we need to add an `AmberGBSAGenerator` in the future?

**Comment by kyleabeauchamp** [comment]
We already have an issue on the OpenMM tracker, so why not leave it at that.  

I think the issue tracker should be reserved for things that we have plans to fix on some finite timescale, as otherwise it becomes impossible to triage tasks effectively.

**Comment by jchodera** [comment]
I believe labels and target releases can be used for this purpose.

**Comment by jchodera** [comment]
Also, we already have code for this---we just have to move it from our [`gbff`](https://github.com/choderalab/gbff) project.  So I don't think it's unreasonable to say this can be done on a finite timescale.

**Comment by kyleabeauchamp** [comment]
It's not clear to me that the code even belongs in this repo.

**Comment by jchodera** [comment]
Eventually, there are a number of things (like this) that belong in the OpenMM repo, but we can't put unstable code in that repo since it is a stable codebase that many people use.  Putting it here is logical, since without it, you can't use small molecules with GB.

**Comment by kyleabeauchamp** [comment]
We can use the AmberTools pipeline, though.  I personally think we should deprecate the ffXML pipeline for small molecules because we do not have enough software engineers to maintain more our own forcefield codebase.  

Again, you are free to do what you like here--I'm just giving my advice on how we can get science done given the limited number of developer-hours that we have.

**Comment by jchodera** [comment]
This sounds like a larger discussion best had in person.
