### ISSUE TITLE
Example packaging the FreeSolv small molecule database into a single ffxml file

### ISSUE THREAD

**Issue by jchodera** [choderalab/openmoltools#49]
I was actually hoping to have an example that packaged the entire FreeSolv small molecule database into a single OpenMM ForceField-compatible ffxml file, since we could use this for various OpenMM-dependent forcefield parameterization experiments.

I'll open a PR to try to do this.

**Comment by kyleabeauchamp** [comment]
I think we should close this for now, as IMHO we still prefer to use Amber inpcrd / prmtop files for most small molecule work.  We can re-open later as this issue resurfaces.
