### ISSUE TITLE
Discuss what formats gaff2xml should accept

### ISSUE THREAD

**Issue by jchodera** [choderalab/openmoltools#54]
We should discuss what formats `gaff2xml` should accept to build an output `ffxml` file.

We often deal with the following formats:
* A Tripos `mol2` file containing one or more ligands
* An `sdf` file containing one or more ligands
* A `pdb` file containing one or more ligands as `HETATM` records
  * These files may not have corresponding `CONECT` records

We may also want to support additional formats for omnia tool interoperability, such as:
* OpenMM `Topology` objects
* mdtraj`Topology` objects

Any others I'm forgetting?

**Comment by davidlmobley** [comment]
@jchodera , can this be closed? (If I don't hear from you I'll assume so and you can re-open if it's needed).

**Comment by jchodera** [comment]
WIll close for now. Eventually, we may want to standardize a representation for how molecules are passed around (e.g. `openeye.oechem.OEMol` or RDKit molecule).
