### ISSUE TITLE
Change travis-ci binstar package upload from gaff2xml-dev to gaff2xml

### ISSUE THREAD

**Issue by jchodera** [choderalab/openmoltools#69]
I think we should be just uploading to a `gaff2xml` package, with the version string set to `dev`.  It doesn't seem to make sense to have both `gaff2xml` with the version string set to release numbers and a separate `gaff2xml-dev` with the version string set to `dev`, since we can simply specify the dev version with `conda install gaff2xml=dev`

**Comment by kyleabeauchamp** [comment]
I think this scheme was decided against, per discussion in #70
